// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1xpgc1in-bzrJa7eETjJGJ8nZQxAWfQ',
    appId: '1:243712887789:web:a4e1a2b05cc06ac16eb5e4',
    messagingSenderId: '243712887789',
    projectId: 'babailon',
    authDomain: 'babailon.firebaseapp.com',
    storageBucket: 'babailon.firebasestorage.app',
    measurementId: 'G-X90Y9QS3PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsVU2AndQ8ia7ajsPr-L-uDycC0cSrCsc',
    appId: '1:243712887789:android:1888fd822c13ca766eb5e4',
    messagingSenderId: '243712887789',
    projectId: 'babailon',
    storageBucket: 'babailon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3tYmKiGuEimJaBLB6HAPwJF36ISXDWs0',
    appId: '1:243712887789:ios:577b39ab1fa7af1b6eb5e4',
    messagingSenderId: '243712887789',
    projectId: 'babailon',
    storageBucket: 'babailon.firebasestorage.app',
    iosBundleId: 'com.example.babellion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3tYmKiGuEimJaBLB6HAPwJF36ISXDWs0',
    appId: '1:243712887789:ios:577b39ab1fa7af1b6eb5e4',
    messagingSenderId: '243712887789',
    projectId: 'babailon',
    storageBucket: 'babailon.firebasestorage.app',
    iosBundleId: 'com.example.babellion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf1xpgc1in-bzrJa7eETjJGJ8nZQxAWfQ',
    appId: '1:243712887789:web:1bcd79a97ebed0a26eb5e4',
    messagingSenderId: '243712887789',
    projectId: 'babailon',
    authDomain: 'babailon.firebaseapp.com',
    storageBucket: 'babailon.firebasestorage.app',
    measurementId: 'G-PGK98140EW',
  );
}
